### ISSUE TITLE
angular5  bug

### ISSUE THREAD

**Issue by miaozhenkun** [zwq8299174/ionic-alpha-scroll#3]
angular5    NgTemplateOutlet＃ngOutletContext已被删除，已被弃用。
使用NgTemplateOutlet＃ngTemplateOutletContext代替。

**Comment by giscafer** [comment]
`<ng-template [ngTemplateOutlet]="itemTemplate" [ngTemplateOutletContext]="{'item': item, 'currentPageClass': currentPageClass}" *ngIf="!item.isDivider">`

**Comment by miaozhenkun** [comment]
OK.  THANKS
